/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState } from "react";
import Header from "./components/Header";
import Hero from "./components/Hero";
import Experience from "./components/Experience";
import FeaturedMenu from "./components/FeaturedMenu";
import SignatureDishes from "./components/SignatureDishes";
import AIConcierge from "./components/AIConcierge";
import SeatingVisualizer from "./components/SeatingVisualizer";
import DeliveryEstimator from "./components/DeliveryEstimator";
import LifestyleGallery from "./components/LifestyleGallery";
import CartDrawer from "./components/CartDrawer";
import MobileStickyNav from "./components/MobileStickyNav";
import Footer from "./components/Footer";

import { MenuItem, CartItem } from "./types";
import { MENU_ITEMS } from "./data";

export default function App() {
  const [cart, setCart] = useState<CartItem[]>([]);
  const [isCartOpen, setIsCartOpen] = useState<boolean>(false);
  const [isReservationOpen, setIsReservationOpen] = useState<boolean>(false);

  // Cart operations
  const handleAddToCart = (item: MenuItem) => {
    setCart((prev) => {
      const exists = prev.find((c) => c.item.id === item.id);
      if (exists) {
        return prev.map((c) =>
          c.item.id === item.id ? { ...c, quantity: c.quantity + 1 } : c
        );
      }
      return [...prev, { item, quantity: 1, customNote: "" }];
    });
    // Visual micro feedback: open cart automatically so the user is secure that it was added!
    setIsCartOpen(true);
  };

  const handleUpdateQuantity = (itemId: string, newQty: number) => {
    if (newQty <= 0) {
      handleRemoveItem(itemId);
      return;
    }
    setCart((prev) =>
      prev.map((c) => (c.item.id === itemId ? { ...c, quantity: newQty } : c))
    );
  };

  const handleRemoveItem = (itemId: string) => {
    setCart((prev) => prev.filter((c) => c.item.id !== itemId));
  };

  const handleClearCart = () => {
    setCart([]);
  };

  // Connects suggestions from AI guide seamlessly to our Cart Drawer
  const handleAddSpecialItem = (name: string, priceText: string) => {
    const found = MENU_ITEMS.find((m) => m.name.toLowerCase() === name.toLowerCase());
    if (found) {
      handleAddToCart(found);
    } else {
      const p = parseInt(priceText.replace(/[^0-9]/g, "")) || 400;
      const parsedItem: MenuItem = {
        id: `suggest-${Date.now()}`,
        name,
        category: "Tea Sommelier Suggestion",
        price: p,
        description: "Special pairing choice generated by our Live Taste AI Guide to custom match your emotional state.",
        imageUrl: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&q=80&w=500",
        rating: 4.9,
        spiceLevel: 0,
        prepTime: "9 mins"
      };
      handleAddToCart(parsedItem);
    }
  };

  // Elegant scroll mapping alignment offsetting height of Fixed Header (80px)
  const handleScrollToSection = (sectionId: string) => {
    const element = document.getElementById(sectionId);
    if (element) {
      const yOffset = -80; 
      const y = element.getBoundingClientRect().top + window.pageYOffset + yOffset;
      window.scrollTo({ top: y, behavior: "smooth" });
    }
  };

  const cartCount = cart.reduce((acc, curr) => acc + curr.quantity, 0);

  return (
    <div className="min-h-screen bg-brand-charcoal text-brand-cream font-sans relative antialiased leading-relaxed pb-12 lg:pb-0">
      
      {/* HEADER SECTION */}
      <Header
        onCartOpen={() => setIsCartOpen(true)}
        cartItemCount={cartCount}
        onReservationOpen={() => setIsReservationOpen(true)}
        onScrollToSection={handleScrollToSection}
      />

      {/* CORE HERO SECTION */}
      <Hero
        onScrollToSection={handleScrollToSection}
        onReservationOpen={() => setIsReservationOpen(true)}
      />

      {/* DETAILED AMBIENCE PILLARS */}
      <Experience />

      {/* INTERACTIVE SIGNATURE CUISINES */}
      <SignatureDishes onAddToCart={handleAddToCart} />

      {/* DYNAMIC BACKEND AI TEA SOMMELIER CONCIERGE */}
      <AIConcierge onAddSpecialItem={handleAddSpecialItem} />

      {/* FULL ALIGNED INTERACTIVE MENU SEARCH & FILTER GUEST CATALOG */}
      <FeaturedMenu onAddToCart={handleAddToCart} />

      {/* GEOLOGICAL ESTIMATOR DELIVERY PORTAL FOR MULTAN SECTORS */}
      <DeliveryEstimator />

      {/* SOCIAL LIFESTYLE HIGHLIGHTS INSTAGRAM FEED BLOCKS */}
      <LifestyleGallery />

      {/* FINAL FOOTER */}
      <Footer />

      {/* SLIDING SHOPPING CART DRAWER */}
      <CartDrawer
        isOpen={isCartOpen}
        onClose={() => setIsCartOpen(false)}
        cartItems={cart}
        onUpdateQuantity={handleUpdateQuantity}
        onRemoveItem={handleRemoveItem}
        onClearCart={handleClearCart}
      />

      {/* POPUP INTERACTIVE TABLE RESERVATION MODAL WITH SEATING GRAPHICS */}
      <SeatingVisualizer
        isOpen={isReservationOpen}
        onClose={() => setIsReservationOpen(false)}
      />

      {/* SMART MOBILE THUMB-DRIVEN BOTTOM FIXED ACTIONS BAR */}
      <MobileStickyNav
        onScrollToSection={handleScrollToSection}
        onReservationOpen={() => setIsReservationOpen(true)}
        onCartOpen={() => setIsCartOpen(true)}
        cartItemCount={cartCount}
      />

    </div>
  );
}
